aws.accessKeyId=test
aws.secretAccessKey=test
aws.region=us-east-1

aws.s3.bucket-name=meu-bucket-local
aws.s3.endpoint=http://localhost:4566
aws.s3.path-style-access=true

spring.datasource.url=jdbc:postgresql://localhost:5432/salestone
spring.datasource.username=postgres
spring.datasource.password=root