spring.application.name=salestone
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev
spring.security.oauth2.resourceserver.jwt.jws-algorithms=HS256

# OpenAI Configuration
openai.api.key=${OPENAI_API_KEY:mock-api-key}
openai.model=gpt-4
openai.api.url=https://api.openai.com/v1/chat/completions
spring.ai.vertex.ai.embedding.options.model=text-embedding-004
# Para o Chat Gemini
spring.ai.vertex.ai.gemini.project-id=gen-lang-client-0110643518
spring.ai.vertex.ai.gemini.location=southamerica-east1

# Para o Embedding (Obrigatório para o PgVectorStore)
spring.ai.vertex.ai.embedding.project-id=gen-lang-client-0110643518
spring.ai.vertex.ai.embedding.location=southamerica-east1
